// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5gazrh4zGA-929so2PhGTxFB6fi8Ah9k',
    appId: '1:831378661778:web:bdbbaae510e15b474fa14b',
    messagingSenderId: '831378661778',
    projectId: 'try-roop',
    authDomain: 'try-roop.firebaseapp.com',
    storageBucket: 'try-roop.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQvZKECVdDSmaKKHPES6IlOvzI4jxpHh8',
    appId: '1:831378661778:android:1cb6595887cbb3dc4fa14b',
    messagingSenderId: '831378661778',
    projectId: 'try-roop',
    storageBucket: 'try-roop.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHLCybWjTbB_vV41Qi37oyKjY824q6CVI',
    appId: '1:831378661778:ios:2789cfdd90fdf59c4fa14b',
    messagingSenderId: '831378661778',
    projectId: 'try-roop',
    storageBucket: 'try-roop.firebasestorage.app',
    iosBundleId: 'com.tryroop.tryroopCampusLiveFlutter',
  );
}
